// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "4cAVSGU2zrHxLbFlDRSCDbngeyMdHsPPnLpl5LWOvPh2SPJjSpTiXVFqzQlHT3rYMv4V74";
}
}
}

